---
development:
  :ZZA_ID: staging.photos/web
  :MIXPANEL_TOKEN: 17540e499e4c7032071b48abcbfeb742
  :GOOGLE_ANALYTICS_TOKEN: UA-18597985-4

perftest:
  :ZZA_ID: dev.photos/web
  :MIXPANEL_TOKEN: 17540e499e4c7032071b48abcbfeb742
  :GOOGLE_ANALYTICS_TOKEN: UA-18597985-4

test:
  :ZZA_ID: dev.photos/web
  :MIXPANEL_TOKEN: 17540e499e4c7032071b48abcbfeb742
  :GOOGLE_ANALYTICS_TOKEN: UA-18597985-4

photos_production:
  :ZZA_ID: photos/web
  :MIXPANEL_TOKEN: c4d7b3457d0051550aad9a7a76ace17e
  :GOOGLE_ANALYTICS_TOKEN: UA-18597985-5

photos_staging:
  :ZZA_ID: staging.photos/web
  :MIXPANEL_TOKEN: 17540e499e4c7032071b48abcbfeb742
  :GOOGLE_ANALYTICS_TOKEN: UA-18597985-4

eytest:
  :ZZA_ID: staging.photos/web
  :MIXPANEL_TOKEN: 17540e499e4c7032071b48abcbfeb742
  :GOOGLE_ANALYTICS_TOKEN: UA-18597985-4
